apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "chatbot.fullname" . }}
spec:
  serviceName: {{ include "chatbot.fullname" . }}-headless
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "chatbot.fullname" . }}
  template:
    metadata:
      labels:
        app: {{ include "chatbot.fullname" . }}
    spec:
      containers:
        - name: kubernetes-chatbot
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: ZOO_MY_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.labels['statefulset.kubernetes.io/pod-index']
          ports:
            - containerPort: {{ .Values.zkClientPort }}
              name: client
            - containerPort: {{ .Values.zkServerPort }}
              name: server
            - containerPort: {{ .Values.zkElectionPort }}
              name: leader-election
            - containerPort: {{ .Values.zkAppPort }}
              name: chatbot
          volumeMounts:
            - name: data-volume
              mountPath: /app
          # The `command` block was removed from here. This allows the container
          # to use the `ENTRYPOINT` defined in the Dockerfile.
          # The `zkapp-volume` is no longer needed since we are running the JAR
          # from the Docker image directly.
      volumes:
        - name: data-volume
          persistentVolumeClaim:
            claimName: {{ include "chatbot.fullname" . }}-pvc
        # The `zkapp-volume` definition was removed from here.
