# version: '3.8'  # Specify the Compose file version; deprecated now

services:
  zkApp1:
    image: zkapp:v1
    hostname: zkApp1
    entrypoint: ["/chatbot-entrypoint.sh"]
    restart: always
    ports:
      - "2181:2181"
      - "3001:3000"
      - "3101:3100"
      - "8081:8080"
    volumes:
      - zkApp1-logs:/logs
      - zkApp1-dataDir:/data
      - zkApp1-dataLogDir:/datalog
    environment:
      ZOO_MY_ID: 1
      ZOO_STANDALONE_ENABLED: false
      ZOO_MAX_SESSION_TIMEOUT: 20000
      ZOO_TICK_TIME: 2000
      ZOO_INIT_LIMIT: 10
      ZOO_SYNC_LIMIT: 5
      ZOO_ADMINSERVER_ENABLED: true
      ZOO_SERVERS: server.1=zkApp1:2888:3888 server.2=zkApp2:2888:3888 server.3=zkApp3:2888:3888
    networks:
      - zookeeper-cluster

  zkApp2:
    image: zkapp:v1
    hostname: zkApp2
    entrypoint: ["/chatbot-entrypoint.sh"]
    restart: always
    ports:
      - "2182:2181"
      - "3002:3000"
      - "3102:3100"
      - "8082:8080"
    volumes:
      - zkApp2-logs:/logs
      - zkApp2-dataDir:/data
      - zkApp2-dataLogDir:/datalog
    environment:
      ZOO_MY_ID: 2
      ZOO_STANDALONE_ENABLED: false
      ZOO_MAX_SESSION_TIMEOUT: 20000
      ZOO_TICK_TIME: 2000
      ZOO_INIT_LIMIT: 10
      ZOO_SYNC_LIMIT: 5
      ZOO_ADMINSERVER_ENABLED: true
      ZOO_SERVERS: server.1=zkApp1:2888:3888 server.2=zkApp2:2888:3888 server.3=zkApp3:2888:3888
    networks:
      - zookeeper-cluster

  zkApp3:
    image: zkapp:v1
    hostname: zkApp3
    entrypoint: ["/chatbot-entrypoint.sh"]
    restart: always
    ports:
      - "2183:2181"
      - "3003:3000"
      - "3103:3100"
      - "8083:8080"
    volumes:
      - zkApp3-logs:/logs
      - zkApp3-dataDir:/data
      - zkApp3-dataLogDir:/datalog
    environment:
      ZOO_MY_ID: 3
      ZOO_STANDALONE_ENABLED: false
      ZOO_MAX_SESSION_TIMEOUT: 20000
      ZOO_TICK_TIME: 2000
      ZOO_INIT_LIMIT: 10
      ZOO_SYNC_LIMIT: 5
      ZOO_ADMINSERVER_ENABLED: true
      ZOO_SERVERS: server.1=zkApp1:2888:3888 server.2=zkApp2:2888:3888 server.3=zkApp2:2888:3888
    networks:
      - zookeeper-cluster

# to remove the volumes, run: docker compose down --volumes
volumes:
  zkApp1-dataDir:
  zkApp1-dataLogDir:
  zkApp1-logs:
  zkApp2-dataDir:
  zkApp2-dataLogDir:
  zkApp2-logs:
  zkApp3-dataDir:
  zkApp3-dataLogDir:
  zkApp3-logs:

networks:
  zookeeper-cluster:
    driver: bridge  # Optional: Specify the network driver (defaults to 'bridge')
    enable_ipv6: false  # Optional: Disable IPv6
#    driver_opts:
#      com.docker.network.bridge.name: 'zookeeper-cluster' # Optional: Specific driver options
      #external: true  # indicates that this network is not being created by Docker Compose itself.
      #Instead, it's referencing a network that has already been created outside of Docker Compose.
    # docker network create --driver bridge --ipv6=false zookeeper-cluster



#version: '3.8'  # Specify the Compose file version
#
#services:
#  node1:
#    image: zkapp:v1  # The Docker image for your node
#    # ... other configurations (ports, volumes, environment variables, etc.)
#
#  node2:
#    image: zkapp:v1
#    # ... (configurations can be the same or different)
#
#  node3:
#    image: zkapp:v1
#    # ...
#
#networks:
#  my_app_network:  # Named network
#    driver: bridge  # Optional: Specify the network driver (defaults to 'bridge')
#    driver_opts:
#      com.docker.network.bridge.name: 'zookeeper-cluster' # Optional: Specific driver options