apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "theApp.fullname" . }}
spec:
  serviceName: {{ include "theApp.fullname" . }}-headless
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "theApp.fullname" . }}
  # updateStrategy:
  #   type: RollingUpdate
  # podManagementPolicy: OrderedReady
  template:
    metadata:
      labels:
        app: {{ include "theApp.fullname" . }}
    spec:
      containers:
        - name: kubernetes-theApp
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: ZOO_MY_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.labels['statefulset.kubernetes.io/pod-index']
          # resources:
          #   requests:
          #     memory: "500Mi"
          #     cpu: "0.25"
          ports:
            - containerPort: {{ .Values.zkClientPort }}
              name: client
            - containerPort: {{ .Values.zkServerPort }}
              name: server
            - containerPort: {{ .Values.zkElectionPort }}
              name: leader-election
            - containerPort: {{ .Values.zkAppPort }}
              name: theApp
          volumeMounts:
            - name: data-volume
              mountPath: /app
            - name: config
              mountPath: /my-config
              readOnly: true
            - mountPath: /{{ include "theApp.fullname" . }}
              name: zkapp-volume
          command:
            - sh
            - -c
            - "cd /conf && /bin/rm * && cp /my-config/* .&&
            bash -x /conf/start-zookeeper.sh \
            -conf_dir=/conf --servers={{ .Values.replicaCount }} \
            --data_dir=/data --data_log_dir=/data/log --log_dir=/logs \
            --client_port={{ .Values.zkClientPort }} \
            --election_port={{ .Values.zkElectionPort }} \
            --server_port={{ .Values.zkServerPort }} \
            --tick_time=2000 --init_limit=10 --sync_limit=5 --heap={{ .Values.zkHeap }} \
            --max_client_cnxns=60 --snap_retain_count=3 --purge_interval=12 \
            --max_session_timeout={{ .Values.zkMaxSessionTimeout}} \
            --min_session_timeout={{ .Values.zkMinSessionTimeout }} \
            --log_level=ERROR"
      volumes:
        - name: config
          configMap:
            name: {{ include "theApp.fullname" . }}-configmap

        - name: data-volume
          persistentVolumeClaim:
            claimName: {{ include "theApp.fullname" . }}-pvc

        - name: zkapp-volume
          hostPath:
            path: /{{ include "theApp.fullname" . }}
            type: Directory