apiVersion: v1
kind: Service
metadata:
  name: {{ include "theApp.fullname" . }}-service
  labels:
    app: {{ include "theApp.fullname" . }}
spec:
  ports:
    - port: 2181
      name: client
  selector:
    app: {{ include "theApp.fullname" . }}