apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "theApp.fullname" . }}-pvc
spec:
  accessModes:
    - {{ .Values.storage.accessModes }}
  resources:
    requests:
      storage: {{ .Values.storage.size }}